openapi: 3.1.0
info:
  title: Axon Server REST Applications Queries API
  description: The Axon Server REST API provides HTTP endpoints for managing the Axon Server event store, command routing, query handling, application contexts, users, and cluster configuration.
  version: 4.9.0
  contact:
    name: AxonIQ
    url: https://www.axoniq.io/
  license:
    name: AxonIQ Open Source License
    url: https://www.axoniq.io/
servers:
- url: '{baseUrl}/v1'
  description: Axon Server
  variables:
    baseUrl:
      default: http://localhost:8024
tags:
- name: Queries
paths:
  /queries:
    get:
      operationId: listQueryHandlers
      summary: Axon Framework - List Query Handlers
      description: Returns registered query handlers.
      tags:
      - Queries
      parameters:
      - name: context
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryHandler'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    QueryHandler:
      type: object
      properties:
        query:
          type: string
        clientId:
          type: string
        componentName:
          type: string
        resultName:
          type: string
